[package]
name = "rust-evm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.11.1"
log = "*"
env_logger = "*"
test-env-log = "0.2.8"